python3 wc.py haizeiwang
python3 wc.py xiaoshenke
python3 wc.py jinsheng
python3 wc.py quanlideyouxi1
python3 wc.py quanlideyouxi2
python3 wc.py quanlideyouxi3
python3 wc.py quanlideyouxi4
python3 wc.py quanlideyouxi5
python3 wc.py quanlideyouxi6
python3 wc.py quanlideyouxi7
python3 wc.py xingjichuanyue
